apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: blazrupnik/rso-comments:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: comments
spec:
  type: ClusterIP
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: comments

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: comments
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: comments-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
status:
  currentReplicas: 1
  desiredReplicas: 1
  currentCPUUtilizationPercentage: 0