apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
        - name: ratings
          image: blazrupnik/rso-ratings:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: ratings

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ratings
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ratings-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
status:
  currentReplicas: 1
  desiredReplicas: 1
  currentCPUUtilizationPercentage: 0